//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.28 at 12:11:55 PM IST 
//


package com.mcg.batch.events.notification.support;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mcg.batch.events.notification.support package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EventNotification_QNAME = new QName("http://www.sc.com/smartbatch/notification-1-0", "eventNotification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mcg.batch.events.notification.support
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EventNotification }
     * 
     */
    public EventNotification createEventNotification() {
        return new EventNotification();
    }

    /**
     * Create an instance of {@link Steps }
     * 
     */
    public Steps createSteps() {
        return new Steps();
    }

    /**
     * Create an instance of {@link DataSet }
     * 
     */
    public DataSet createDataSet() {
        return new DataSet();
    }

    /**
     * Create an instance of {@link CustomVariable }
     * 
     */
    public CustomVariable createCustomVariable() {
        return new CustomVariable();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventNotification }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sc.com/smartbatch/notification-1-0", name = "eventNotification")
    public JAXBElement<EventNotification> createEventNotification(EventNotification value) {
        return new JAXBElement<EventNotification>(_EventNotification_QNAME, EventNotification.class, null, value);
    }

}
